# Divided into 4 cmds because of line-length limitation

iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"1.vcd\"" 1.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"1a.vcd\"" 1a.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"2.vcd\"" 2.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"3.vcd\"" 3.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"4.vcd\"" 4.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"5.vcd\"" 5.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"6.vcd\"" 6.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"7.vcd\"" 7.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"8.vcd\"" 8.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"9.vcd\"" 9.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"10.vcd\"" 10.v && sleep 1 && vvp simout.vvp

iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"11.vcd\"" 11.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"12.vcd\"" 12.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"13.vcd\"" 13.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"14.vcd\"" 14.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"15.vcd\"" 15.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"16.vcd\"" 16.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"17.vcd\"" 17.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"18.vcd\"" 18.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"18a.vcd\"" 18a.v && sleep 1 && vvp simout.vvp

iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"19.vcd\"" 19.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"20.vcd\"" 20.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"20a.vcd\"" 20a.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"21.vcd\"" 21.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"21a.vcd\"" 21a.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"22.vcd\"" 22.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"22a.vcd\"" 22a.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"23.vcd\"" 23.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"24.vcd\"" 24.v && sleep 1 && vvp simout.vvp

iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"25.vcd\"" 25.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"26.vcd\"" 26.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"27.vcd\"" 27.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"27a.vcd\"" 27a.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"28.vcd\"" 28.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"29.vcd\"" 29.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"29a.vcd\"" 29a.v && sleep 1 && vvp simout.vvp && iverilog -g2012 -I.. -osimout.vvp -D"DUMP_FILE_NAME=\"30.vcd\"" 30.v && sleep 1 && vvp simout.vvp
